filters:
  roe_min: 0
  debt_to_equity_max: 999
  free_cash_flow_min: -999999
  revenue_cagr_5yr_min: -999
  pat_cagr_5yr_min: -999
  operating_profit_margin_min: -999
  pe_ratio_max: 9999
  pb_ratio_max: 9999
  dividend_yield_min: 0
  interest_coverage_min: 0
  market_cap_min: 0
  net_profit_min: -999999
  eps_cagr_5yr_min: -999
  asset_turnover_min: 0
  sales_min: 0
